#!/bin/bash -x

# ogg123 /usr/share/sounds/freedesktop/stereo/service-logout.oga
# aplay sounds/disconnect.wav
espeak-ng -s 140 "Waiting for connection"

# reenable wifi - TODO: check what permissions bt-speaker might need for this (netdev group?)
# ifconfig wlan0 up &
