#!/bin/bash -x
#
# Commands to run after startup of bt_speaker

espeak-ng 'bluetooth ready.
pin code is
1
2
3
4'

# disconnect wifi to prevent dropouts - TODO: check what permissions bt-speaker might need for this (netdev group?)
# ifconfig wlan0 down &
